DROP TABLE MDBOARD;
DROP SEQUENCE MDBOARDSEQ;

CREATE SEQUENCE MDBOARDSEQ;
CREATE TABLE MDBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MDBOARD 
VALUES(MDBOARDSEQ.NEXTVAL,'냥냥','안녕하세요','저는냥냥입니다',SYSDATE);

INSERT INTO MDBOARD VALUES(MDBOARDSEQ.NEXTVAL, '관리자', '멀티딜리트 테스트', '재밌네', SYSDATE);

INSERT INTO MDBOARD VALUES(MDBOARDSEQ.NEXTVAL, '지나가던 1인', '천천히 해주세요', '안녕하세요', SYSDATE);

SELECT* FROM MDBOARD ORDER BY SEQ DESC;