DROP SEQUENCE FREECOMMSEQ;
DROP TABLE FREECOMM;

--글번호,아이디,제목,내용,작성일
--나중에 추가할것 조회수,비밀번호 
CREATE SEQUENCE FREECOMMSEQ;
CREATE TABLE FREECOMM(
	FREECOMM_SEQ NUMBER PRIMARY KEY,
	FREECOMM_ID VARCHAR2(500) NOT NULL,
	FREECOMM_TITLE VARCHAR2(500) NOT NULL,
	FREECOMM_CONTENT VARCHAR2(1500) NOT NULL,
	FREECOMM_REGDATE DATE NOT NULL
);
INSERT INTO FREECOMM VALUES(FREECOMMSEQ.NEXTVAL,'아이디','제목' ,'내용',SYSDATE);

INSERT INTO FREECOMM VALUES(FREECOMMSEQ.NEXTVAL,'id1','title1' ,'content1',SYSDATE);
INSERT INTO FREECOMM VALUES(FREECOMMSEQ.NEXTVAL,'id2','title2' ,'content2',SYSDATE);

SELECT * FROM FREECOMM ORDER BY FREECOMM_SEQ DESC;
SELECT * FROM ALL_TAB_COLUMNS 
WHERE TABLE_NAME = ' FREECOMM ' ;
SELECT * FROM USER_TAB_COLUMNS;
--paging 
