DROP TABLE MDBOARD;
DROP SEQUENCE MDBOARDSEQ;

CREATE SEQUENCE MDBOARDSEQ;
CREATE TABLE MDBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MDBOARD 
VALUES(MDBOARDSEQ.NEXTVAL,'냥냥이','제목입니다.','MULDEL이면 여러개 해야하나 ',SYSDATE);


SELECT * FROM MDBOARD ORDER BY SEQ DESC;